---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["forwarded_port", {guest: 80, host: 8080}]
      - ["private_network", {ip: "192.168.33.1"}]

suites:
  - name: default
    run_list:
      - recipe[ghostblog::default]
    attributes:
