---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.4}]
      customize:
        cpus: 4
        memory: 4096

  - name: ubuntu-14.04
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.5}]
      customize:
        cpus: 4
        memory: 4096

  - name: ubuntu-16.04
    driver_config:
      network:
      - ["private_network", {ip: 192.168.150.6}]
      customize:
        cpus: 4
        memory: 4096
suites:
  - name: default
    run_list:
      - recipe[test::default] # invokes test cookbook (`test/cookbooks/test`)
    attributes:
